/**
 * SIGNMIND — Tailwind CSS Configuration
 * Cybernetic Dark-Mode Design System & Biometric HUD Tokens
 * @type {import('tailwindcss').Config}
 */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2c3039",
        "surface-container-lowest": "#0a0e16",
        "secondary-fixed": "#e9ddff",
        "primary-fixed-dim": "#00e293",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed": "#50ffaf",
        "on-secondary-fixed": "#23005c",
        "on-error": "#690005",
        "on-secondary-container": "#c4abff",
        "secondary-fixed-dim": "#d0bcff",
        "tertiary-container": "#ffce95",
        "surface-container-highest": "#31353e",
        "on-surface-variant": "#b9cbbd",
        "on-error-container": "#ffdad6",
        "primary": "#cdffde",
        "inverse-primary": "#006c44",
        "on-surface": "#dfe2ee",
        "surface-container-high": "#262a33",
        "surface": "#0f131c",
        "on-primary-fixed": "#002111",
        "on-tertiary": "#472a00",
        "on-tertiary-fixed": "#2a1700",
        "on-background": "#dfe2ee",
        "on-secondary-fixed-variant": "#5516be",
        "secondary-container": "#571bc1",
        "secondary": "#d0bcff",
        "outline-variant": "#3b4a40",
        "surface-variant": "#31353e",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-dim": "#0f131c",
        "tertiary": "#fff1e4",
        "surface-container-low": "#181c24",
        "surface-tint": "#00e293",
        "on-primary-container": "#006b43",
        "on-tertiary-container": "#835200",
        "primary-container": "#00f5a0",
        "on-secondary": "#3c0091",
        "on-primary-fixed-variant": "#005232",
        "tertiary-fixed": "#ffddb8",
        "inverse-surface": "#dfe2ee",
        "outline": "#849588",
        "background": "#0f131c",
        "surface-bright": "#353942",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "surface-container": "#1c2028",
        "on-primary": "#003921",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "margin-desktop": "3rem",
        "gutter": "1.5rem",
        "unit-lg": "1.5rem",
        "unit-xl": "2rem",
        "unit-2xs": "0.25rem",
        "unit-2xl": "3rem",
        "unit-xs": "0.5rem",
        "unit-md": "1rem",
        "margin-tablet": "2rem",
        "unit-3xl": "4rem",
        "unit-sm": "0.75rem",
      },
      fontFamily: {
        "label-telemetry": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-code-metric": ["Space Grotesk", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-telemetry": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-code-metric": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
